# Notes importantes (pour éviter les pièges)
# id = ton Host alias (celui que tu taperas : ssh github-lddvlp)
# label = juste du texte d’affichage (menu/status)
# hostname = HostName
# username = User
# port = Port
# keyname = nom du fichier de clé dans ~/.ssh/ (sans .pub)

# id|label|hostname|username|port|keyname
planethoster-loicdrouet-com|PlanetHoster loicdrouet.com|node30-eu.n0c.com|loicvtve|5022|planethoster-loicdrouet-com_loicvtve
planethoster-ldbug-com|PlanetHoster ldbug.com|node266-eu.n0c.com|dwmkyvke|5022|planethoster-ldbug-com_dwmkyvke
github-lddvlp|GitHub lddvlp|github.com|git|22|github-lddvlp_git
gitlab-lddvlp|GitLab lddvlp|gitlab.com|git|22|gitlab-lddvlp_git
bitbucket-lddvlp|Bitbucket lddvlp|bitbucket.org|git|22|bitbucket-lddvlp_git

