name: Release

on:
  push:
    tags:
      - "v*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh ${GITHUB_REF_NAME}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip